version: "3.3"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer_devops
    restart: on-failure
    ports:
      - "9999:9000"
      - "8008:8080"
    volumes:
      - type: volume
        source: portainer_data
        target: /data
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks: 
      - devops_net
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_devops
    user: root:root
    restart: on-failure
    ports:
      - "8088:8080"
      - "443:443"
      - "50000:50000"
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        
    networks: 
      - devops_net
  
  sonarqube:
    image: sonarqube
    container_name: sonar_devops
    restart: on-failure
    ports: 
      - "9000:9000"
    volumes: 
      - type: volume
        source: sonarqube_conf
        target: /opt/sonarqube/conf
      - type: volume
        source: sonarqube_data
        target: /opt/sonarqube/data
      - type: volume
        source: sonarqube_extensions
        target: /opt/sonarqube/extensions
      - type: volume
        source: sonarqube_bundled-plugins
        target: /opt/sonarqube/lib/bundled-plugins
    networks: 
      - devops_net
    environment: 
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db_sonar/sonar

  db_sonar:
    image: postgres
    container_name: db_sonar
    restart: on-failure
    environment: 
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - type: volume
        source: postgresql_data
        target: /var/lib/posgresql/data
    
    networks: 
      - devops_net

networks: 
  devops_net:

volumes:
  portainer_data:

  jenkins_home:
  
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:

  postgresql_data:
