version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_devops
    user: root:root
    restart: on-failure
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        
    networks: 
      - devops_net

networks: 
  devops_net:

volumes:
  portainer_data:

  jenkins_home:

