version: "3"
services: 
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_devops
    volumes: 
      - "./JENKINS:/var/jenkins_home"
    ports: 
      - "8080:8080"
      - "5000:5000"
    networks: 
      - devops_net
  
  sonarqube:
    image: sonarqube
    container_name: sonar_devops
    volumes: 
      - "./SONARQUBE/sonarqube_conf:/opt/sonarqube/conf"
      - "./SONARQUBE/sonarqube_data:/opt/sonarqube/data"
      - "./SONARQUBE/sonarqube_extensions:/opt/sonarqube/extensions"
      - "./SONARQUBE/sonarqube_logs:/opt/sonarqube/logs"
      - "./SONARQUBE/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins"
    ports: 
      - "9000:9000"
    networks: 
      - devops_net
  
networks: 
  devops_net:
